import FooterSection from "@/modules/components/Footer/FooterSection";
import QueryProvider from "@/modules/components/Provider/QueryProvider";
import theme from "@/theme/themeConfig";
import { ConfigProvider } from "antd";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <QueryProvider>
          <ConfigProvider theme={theme}>{children}</ConfigProvider>
        </QueryProvider>
        <FooterSection />
      </body>
    </html>
  );
}
